"""
Anomaly Detection Model — Training Script

What this script does:
  - Reads sensor readings from the Silver layer Parquet files in MinIO
  - Pivots the data into one row per well per time window
    (pressure, temperature, flow_rate, vibration, rpm as features)
  - Trains an Isolation Forest model on normal operating data
  - Evaluates against the simulator's is_anomaly ground truth labels
  - Saves the trained model to ml/model/anomaly_detector.pkl

Why Isolation Forest and not a supervised classifier?
  In production, we never fully trust labels generated by a simulator.
  Real anomalies are defined by domain experts reviewing historical incidents, not by a random flag. 
  Isolation Forest learns the shape of normal operation without relying on labels — making it transferable to real sensor data
  where labels don't exist. We use is_anomaly only for evaluation, not training.
"""

import os
import pickle
import logging
import pandas as pd
import numpy as np
from datetime import datetime, timezone, timedelta

from botocore.client import Config
from pyarrow import fs
import pyarrow.parquet as pq
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.preprocessing import StandardScaler
import mlflow
import mlflow.sklearn

# -- Logging ------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S"
)
log = logging.getLogger(__name__)

# -- Config -------------------------------------------------------------------
MINIO_ENDPOINT   = os.getenv("MINIO_ENDPOINT", "http://localhost:9000")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY", "minioadmin")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY", "minioadmin")
SILVER_BUCKET    = "silver"
SILVER_PREFIX    = "sensor_readings/"
MODEL_DIR        = os.path.join(os.path.dirname(__file__), "model")
MODEL_PATH       = os.path.join(MODEL_DIR, "anomaly_detector.pkl")
SCALER_PATH      = os.path.join(MODEL_DIR, "scaler.pkl")

SENSORS          = ["pressure", "temperature", "flow_rate", "vibration", "rpm"]
FEATURES         = [f"avg_{s}" for s in SENSORS]

# Isolation Forest config
CONTAMINATION    = 0.05   # matches the simulator's 5% anomaly rate
RANDOM_STATE     = 42
N_ESTIMATORS     = 100


def read_silver_from_minio() -> pd.DataFrame:
    """
    Read all Silver Parquet data from MinIO into a pandas DataFrame.
    Uses PyArrow's S3FileSystem for direct Parquet reads without Spark.
    Fast enough for training data that fits in memory.
    """
    log.info("Reading Silver layer from MinIO ...")

    s3 = fs.S3FileSystem(
        endpoint_override=MINIO_ENDPOINT.replace("http://", ""),
        access_key=MINIO_ACCESS_KEY,
        secret_key=MINIO_SECRET_KEY,
        scheme="http"
    )

    dataset = pq.read_table(
        f"{SILVER_BUCKET}/{SILVER_PREFIX}",
        filesystem=s3
    )
    df = dataset.to_pandas()
    log.info(f"  Records loaded: {len(df):,}")
    log.info(f"  Columns: {list(df.columns)}")
    return df


def generate_synthetic_data(n_hours: int = 200) -> pd.DataFrame:
    """
    Generate synthetic sensor readings mirroring sensor_simulator.py.
    Includes deliberately anomalous hours (simulating equipment fault events)
    to enable meaningful model evaluation.

    Normal hours: ~5% anomaly rate (matches simulator baseline)
    Fault hours:  ~40% anomaly rate (simulates a failing pump or pressure spike)
    """
    import numpy as np

    log.info(f"Generating synthetic data for {n_hours} hours ...")

    WELLS = ["WELL-001", "WELL-002", "WELL-003", "WELL-004", "WELL-005"]
    SENSOR_CONFIGS = {
        "pressure":    {"normal": (800, 1200),  "anomaly": (1400, 1800)},
        "temperature": {"normal": (60, 90),     "anomaly": (110, 140)},
        "flow_rate":   {"normal": (50, 150),    "anomaly": (0, 20)},
        "vibration":   {"normal": (0.5, 3.0),   "anomaly": (5.0, 9.0)},
        "rpm":         {"normal": (1200, 1800), "anomaly": (200, 700)},
    }
    READINGS_PER_HOUR = 720
    FAULT_HOUR_PROB   = 0.08   # 8% of hours are fault hours

    rows = []
    base_time = pd.Timestamp("2026-01-01", tz="UTC")
    fault_hours = 0

    for hour in range(n_hours):
        ts = base_time + pd.Timedelta(hours=hour)
        is_fault_hour = np.random.random() < FAULT_HOUR_PROB
        if is_fault_hour:
            fault_hours += 1

        for well in WELLS:
            # In fault hours, one random sensor goes into high-anomaly mode
            fault_sensor = np.random.choice(list(SENSOR_CONFIGS.keys())) \
                if is_fault_hour else None

            for sensor, config in SENSOR_CONFIGS.items():
                # Fault sensor gets 40% anomaly rate; others stay at 5%
                anomaly_prob = 0.40 if (is_fault_hour and sensor == fault_sensor) \
                    else 0.05

                for _ in range(READINGS_PER_HOUR):
                    is_anomaly = np.random.random() < anomaly_prob
                    r = config["anomaly"] if is_anomaly else config["normal"]
                    mid = (r[0] + r[1]) / 2
                    std = (r[1] - r[0]) / 6
                    value = float(np.clip(np.random.normal(mid, std), r[0], r[1]))
                    rows.append({
                        "well_id":     well,
                        "sensor_type": sensor,
                        "value":       value,
                        "is_anomaly":  is_anomaly,
                        "timestamp":   ts
                    })

    df = pd.DataFrame(rows)
    log.info(f"  Generated {len(df):,} synthetic readings")
    log.info(f"  Fault hours injected: {fault_hours}/{n_hours}")
    log.info(f"  Overall anomaly rate: {df['is_anomaly'].mean():.3f}")
    return df


def build_feature_matrix(df: pd.DataFrame) -> pd.DataFrame:
    """
    Pivot raw sensor readings into one row per well per hour.

    Input (one row per reading):
      well_id | sensor_type | value | is_anomaly | timestamp

    Output (one row per well per hour):
      well_id | hour | avg_pressure | avg_temperature | avg_flow_rate | avg_vibration | avg_rpm | anomaly_rate

    This aggregation does two things:
      1. Creates a stable feature vector the model can learn from
      2. Smooths out individual noisy readings — the model learns patterns of abnormal operation, not single spikes
    """
    log.info("Building feature matrix ...")

    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
    df["hour"] = df["timestamp"].dt.floor("h")

    # Pivot: average value per well per sensor per hour
    pivoted = (
        df.groupby(["well_id", "hour", "sensor_type"], observed=True)
        .agg(
            avg_value=("value", "mean"),
            anomaly_count=("is_anomaly", "sum"),
            total_count=("is_anomaly", "count")
        )
        .reset_index()
    )

    # Wide format: one column per sensor
    wide = pivoted.pivot_table(
        index=["well_id", "hour"],
        columns="sensor_type",
        values="avg_value"
    ).reset_index()

    wide.columns = [
        f"avg_{c}" if c in SENSORS else c
        for c in wide.columns
    ]

    # Add anomaly rate per well per hour (for evaluation only)
    anomaly_rate = (
        df.groupby(["well_id", "hour"], observed=True)
        .agg(
            anomaly_rate=("is_anomaly", "mean"),
            is_anomaly_window=("is_anomaly", "mean")  # will threshold below
        )
        .reset_index()
    )

    # A window is "truly anomalous" if its anomaly rate is 2x the expected baseline
    # Expected baseline = 5% (simulator config). 2x = 10% threshold.
    anomaly_rate["is_anomaly_window"] = anomaly_rate["is_anomaly_window"] > 0.10

    feature_df = wide.merge(anomaly_rate, on=["well_id", "hour"])
    feature_df = feature_df.dropna(subset=FEATURES)

    log.info(f"  Feature matrix shape: {feature_df.shape}")
    log.info(f"  Wells: {feature_df['well_id'].unique().tolist()}")
    log.info(f"  Hours: {feature_df['hour'].nunique()}")
    log.info(f"  Anomalous windows: {feature_df['is_anomaly_window'].sum()}")

    return feature_df


def train_model(feature_df: pd.DataFrame):
    """
    Train Isolation Forest on all windows.

    We don't filter out windows with any anomaly — the simulator produces
    ~5% anomalous readings in every window, so filtering by is_anomaly_window
    would leave no training data. Instead we train on all windows and let
    Isolation Forest learn the normal operating envelope from the feature
    distributions. Windows with unusually high anomaly rates or abnormal
    sensor averages will be identified as outliers by the model.
    """
    log.info("Training Isolation Forest ...")
    log.info(f"  Training on all {len(feature_df)} windows")

    X_train = feature_df[FEATURES].values

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)

    model = IsolationForest(
        n_estimators=N_ESTIMATORS,
        contamination=CONTAMINATION,
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
    model.fit(X_train_scaled)

    log.info("  Training complete.")
    return model, scaler


def evaluate_model(model, scaler, feature_df: pd.DataFrame):
    """
    Evaluate on the full dataset using simulator labels as ground truth.

    Isolation Forest returns:
      +1 = normal (inlier)
      -1 = anomaly (outlier)

    We convert to binary (0/1) to compare against is_anomaly labels.
    """
    log.info("Evaluating model ...")

    X_all = scaler.transform(feature_df[FEATURES].values)
    y_true = feature_df["is_anomaly_window"].astype(int).values

    raw_preds = model.predict(X_all)
    y_pred = (raw_preds == -1).astype(int)

    scores = model.score_samples(X_all)
    # score_samples returns anomaly score — lower = more anomalous
    # Negate so higher = more anomalous (matches sklearn convention)
    anomaly_scores = -scores

    log.info("\n" + classification_report(y_true, y_pred,
             target_names=["normal", "anomaly"]))

    if len(np.unique(y_true)) > 1:
        auc = roc_auc_score(y_true, anomaly_scores)
        log.info(f"  ROC-AUC: {auc:.3f}")
    else:
        auc = None
        log.info("  ROC-AUC: skipped (only one class in window)")

    return y_pred, anomaly_scores, auc


def save_model(model, scaler):
    """Save model and scaler to disk for use by the prediction API."""
    os.makedirs(MODEL_DIR, exist_ok=True)
    with open(MODEL_PATH, "wb") as f:
        pickle.dump(model, f)
    with open(SCALER_PATH, "wb") as f:
        pickle.dump(scaler, f)
    log.info(f"  Model saved to {MODEL_PATH}")
    log.info(f"  Scaler saved to {SCALER_PATH}")


def run():
    mlflow.set_experiment("iot-anomaly-detection")

    with mlflow.start_run():
        mlflow.log_param("model_type", "IsolationForest")
        mlflow.log_param("contamination", CONTAMINATION)
        mlflow.log_param("n_estimators", N_ESTIMATORS)
        mlflow.log_param("features", FEATURES)

        # Try real Silver layer data first
        df = read_silver_from_minio()

        # Fall back to synthetic if insufficient hours
        unique_hours = df["timestamp"].dt.floor("h").nunique() if len(df) > 0 else 0
        if unique_hours < 50:
            log.warning(
                f"Only {unique_hours} hours of real data available. "
                f"Supplementing with synthetic data for robust training."
            )
            df_synthetic = generate_synthetic_data(n_hours=200)
            df = pd.concat([df, df_synthetic], ignore_index=True)
            mlflow.log_param("training_data", "real_silver_plus_synthetic")
        else:
            mlflow.log_param("training_data", "real_silver_layer")

        feature_df = build_feature_matrix(df)

        if len(feature_df) < 10:
            log.error("Not enough data to train.")
            return

        model, scaler = train_model(feature_df)
        y_pred, anomaly_scores, auc = evaluate_model(model, scaler, feature_df)

        if auc:
            mlflow.log_metric("roc_auc", auc)

        mlflow.log_metric("training_windows", len(feature_df))
        mlflow.log_metric("anomaly_windows_detected", int(y_pred.sum()))
        mlflow.sklearn.log_model(model, "isolation_forest_model")

        save_model(model, scaler)
        log.info("Training run complete.")


if __name__ == "__main__":
    run()